### ISSUE TITLE
Mobile stylesheet

### ISSUE THREAD

**Issue by bholota** [dominikhajduk/climbing-in-rzeszow#16]
Currently mobile browser renders page with wide, horizontal margins. It's a lot of space wasted.
![screenshot_20180827-090552_chrome](https://user-images.githubusercontent.com/1562442/44645795-27786880-a9d9-11e8-9279-712f5224164d.jpg)

**Comment by dominikhajduk** [comment]
@bholota good point will look on this. Thanks!
